### ISSUE TITLE
[Question] Delete history in Telegram?

### ISSUE THREAD

**Issue by nibogd** [fabianonline/telegram_backup#31]
I don't need to save history of a group which has around 200k messages. I cleared the history and left the group, but the messages still get backed up. Is it possible to completely remove data from the account?

If not, it would be great to add an ID blacklist to Telegram Backup.

**Comment by fabianonline** [comment]
I don't know about the removing-data-from-telegram-part. The blacklist-chat-id-for-the-backup is quite complicated, because the tool's logic doesn't care about different chats at all. If you have 2,000 messages, it will get 2,000 messages without checking which of those messages belong to which chat. So the blacklist part could only ignore messages from those chats when it comes to saving them - but that would be after downloading all those messages, by which it is already too late.
So... all in all I don't really know what I could do to help this issue...

**Comment by nibogd** [comment]
Oh, i see... thanks!
