### ISSUE TITLE
only 1 message getting downloaded :(

### ISSUE THREAD

**Issue by niksud** [fabianonline/telegram_backup#61]
Hi

After running the jar file, only 1 image gets downloaded ( that too of the chat with a user and now of groups) 
![capture](https://user-images.githubusercontent.com/34104514/33390590-67a850ac-d55c-11e7-8c1f-3663c2c1043c.JPG)
 . I cant see any text chat.

I have joined 3 groups with thousand of messages but just 1 message(image) got downloaded

I used the latest jar, java 8. Please help me to download all the chat of the group

**Comment by fabianonline** [comment]
I'm not quite sure what your problem is...

The messages are stored in the database.sqlite file. There may be more than just 1 message in it. 80 KB should be at least a few messages. If you want to get the messages in a readable way, try running the app with `--export html` to get HTML files which can be opened in a browser.

If the groups you joined are supergroups or channels: Those aren't downloaded right now, but I'm workin on it. See ticket #21.
