### ISSUE TITLE
[Feature Request] Don't re-download delete media option

### ISSUE THREAD

**Issue by DrakeTDL** [fabianonline/telegram_backup#82]
As the title says, I am suggesting an option to not re-download media(s) that you have delete.

**Comment by fabianonline** [comment]
Right now I use "does the file exist" as marker that I apparently didn't download it yet. So deleting it doesn't look any different than a file I just didn't download yet.

Instead of deleting the file you can just truncate it to 0 bytes since the code doesn't look at the size. In Linux you can just type `> filename` to "empty" the file.
